// <auto-generated />
using InClass08.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InClass08.Migrations
{
    [DbContext(typeof(tvcInClass09LabCFContext))]
    [Migration("20251017035928_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InClass08.Models.TvcLoaiSanPham", b =>
                {
                    b.Property<long>("tvcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tvcId"));

                    b.Property<string>("tvcMaLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tvcTenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("tvcTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("tvcId");

                    b.HasIndex("tvcMaLoai")
                        .IsUnique();

                    b.ToTable("tvcLoaiSanPham");
                });

            modelBuilder.Entity("InClass08.Models.TvcSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("tvcDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tvcHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tvcLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<string>("tvcMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("tvcSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("tvcTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tvcLoaiSanPhamId");

                    b.ToTable("tvcSanPham");
                });

            modelBuilder.Entity("InClass08.Models.TvcSanPham", b =>
                {
                    b.HasOne("InClass08.Models.TvcLoaiSanPham", "TvcLoaiSanPham")
                        .WithMany("TvcSanPham")
                        .HasForeignKey("tvcLoaiSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvcLoaiSanPham");
                });

            modelBuilder.Entity("InClass08.Models.TvcLoaiSanPham", b =>
                {
                    b.Navigation("TvcSanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
